// <auto-generated />
using System;
using IUE.DesatrasadorMVP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IUE.DesatrasadorMVP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611010153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaClase")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaClase = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 1,
                            Resumen = "Variables, tipos y control de flujo.",
                            Titulo = "Introducción a C#"
                        },
                        new
                        {
                            Id = 2,
                            FechaClase = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 1,
                            Resumen = "Clases, objetos y herencia.",
                            Titulo = "POO en C#"
                        },
                        new
                        {
                            Id = 3,
                            FechaClase = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 2,
                            Resumen = "1FN, 2FN y 3FN explicadas.",
                            Titulo = "Normalización"
                        },
                        new
                        {
                            Id = 4,
                            FechaClase = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MateriaId = 3,
                            Resumen = "Definición epsilon-delta.",
                            Titulo = "Límites y continuidad"
                        });
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "juan.perez@iue.edu.co",
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "maria.lopez@iue.edu.co",
                            Nombre = "María López"
                        });
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Excusa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Excusas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaseId = 1,
                            Descripcion = "Incapacidad médica",
                            Estado = 1,
                            EstudianteId = 1,
                            FechaEnvio = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClaseId = 2,
                            Descripcion = "Problema familiar",
                            Estado = 0,
                            EstudianteId = 1,
                            FechaEnvio = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClaseId = 3,
                            Descripcion = "Viaje académico",
                            Estado = 1,
                            EstudianteId = 2,
                            FechaEnvio = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstudianteId = 1,
                            MateriaId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstudianteId = 1,
                            MateriaId = 2
                        },
                        new
                        {
                            Id = 3,
                            EstudianteId = 2,
                            MateriaId = 1
                        },
                        new
                        {
                            Id = 4,
                            EstudianteId = 2,
                            MateriaId = 3
                        });
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Fundamentos de programación",
                            Nombre = "Programación I"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "SQL y modelado relacional",
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Límites, derivadas e integrales",
                            Nombre = "Cálculo Diferencial"
                        });
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.VideoClase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubidoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId")
                        .IsUnique();

                    b.ToTable("VideoClases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaseId = 1,
                            SubidoEn = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VideoUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                        });
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Clase", b =>
                {
                    b.HasOne("IUE.DesatrasadorMVP.Models.Materia", "Materia")
                        .WithMany("Clases")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Excusa", b =>
                {
                    b.HasOne("IUE.DesatrasadorMVP.Models.Clase", "Clase")
                        .WithMany("Excusas")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IUE.DesatrasadorMVP.Models.Estudiante", "Estudiante")
                        .WithMany("Excusas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Inscripcion", b =>
                {
                    b.HasOne("IUE.DesatrasadorMVP.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IUE.DesatrasadorMVP.Models.Materia", "Materia")
                        .WithMany("Inscripciones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.VideoClase", b =>
                {
                    b.HasOne("IUE.DesatrasadorMVP.Models.Clase", "Clase")
                        .WithOne("VideoClase")
                        .HasForeignKey("IUE.DesatrasadorMVP.Models.VideoClase", "ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Clase", b =>
                {
                    b.Navigation("Excusas");

                    b.Navigation("VideoClase");
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Estudiante", b =>
                {
                    b.Navigation("Excusas");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("IUE.DesatrasadorMVP.Models.Materia", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
